export const SET_REDUX_USER = 'SET_REDUX_USER';
export const SET_DISPLAY_NAME = 'SET_DISPLAY_NAME';
export const REMOVE_REDUX_USER = 'REMOVE_REDUX_USER';
export const ADD_USER_TICKET = 'ADD_USER_TICKET';
export const CLEAR_LOCAL_TICKETS = 'CLEAR_LOCAL_TICKETS';
export const ADD_FIREBASE_USER_TO_LOCAL = 'ADD_FIREBASE_USER_TO_LOCAL';
export const SET_ADMIN = 'SET_ADMIN';
export const CHANGE_COLOR_THEME = 'CHANGE_COLOR_THEME';